// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/nominatim.proto

package nominatim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NominatimResponseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceID     int32                                     `protobuf:"varint,1,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	Licence     string                                    `protobuf:"bytes,2,opt,name=Licence,proto3" json:"Licence,omitempty"`
	OsmType     string                                    `protobuf:"bytes,3,opt,name=OsmType,proto3" json:"OsmType,omitempty"`
	OsmID       int32                                     `protobuf:"varint,4,opt,name=OsmID,proto3" json:"OsmID,omitempty"`
	Boundingbox []*NominatimResponseItem_BoundingboxArray `protobuf:"bytes,5,rep,name=Boundingbox,proto3" json:"Boundingbox,omitempty"`
	Lat         string                                    `protobuf:"bytes,6,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon         string                                    `protobuf:"bytes,7,opt,name=Lon,proto3" json:"Lon,omitempty"`
	DisplayName string                                    `protobuf:"bytes,8,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	Class       string                                    `protobuf:"bytes,9,opt,name=Class,proto3" json:"Class,omitempty"`
	Type        string                                    `protobuf:"bytes,10,opt,name=Type,proto3" json:"Type,omitempty"`
	Importance  string                                    `protobuf:"bytes,11,opt,name=Importance,proto3" json:"Importance,omitempty"`
	Icon        string                                    `protobuf:"bytes,12,opt,name=Icon,proto3" json:"Icon,omitempty"`
}

func (x *NominatimResponseItem) Reset() {
	*x = NominatimResponseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nominatim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NominatimResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NominatimResponseItem) ProtoMessage() {}

func (x *NominatimResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominatim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NominatimResponseItem.ProtoReflect.Descriptor instead.
func (*NominatimResponseItem) Descriptor() ([]byte, []int) {
	return file_proto_nominatim_proto_rawDescGZIP(), []int{0}
}

func (x *NominatimResponseItem) GetPlaceID() int32 {
	if x != nil {
		return x.PlaceID
	}
	return 0
}

func (x *NominatimResponseItem) GetLicence() string {
	if x != nil {
		return x.Licence
	}
	return ""
}

func (x *NominatimResponseItem) GetOsmType() string {
	if x != nil {
		return x.OsmType
	}
	return ""
}

func (x *NominatimResponseItem) GetOsmID() int32 {
	if x != nil {
		return x.OsmID
	}
	return 0
}

func (x *NominatimResponseItem) GetBoundingbox() []*NominatimResponseItem_BoundingboxArray {
	if x != nil {
		return x.Boundingbox
	}
	return nil
}

func (x *NominatimResponseItem) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *NominatimResponseItem) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *NominatimResponseItem) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NominatimResponseItem) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *NominatimResponseItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NominatimResponseItem) GetImportance() string {
	if x != nil {
		return x.Importance
	}
	return ""
}

func (x *NominatimResponseItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type ListNominatimResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nominatimresponse []*NominatimResponseItem `protobuf:"bytes,1,rep,name=nominatimresponse,proto3" json:"nominatimresponse,omitempty"`
}

func (x *ListNominatimResponse) Reset() {
	*x = ListNominatimResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nominatim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNominatimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNominatimResponse) ProtoMessage() {}

func (x *ListNominatimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominatim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNominatimResponse.ProtoReflect.Descriptor instead.
func (*ListNominatimResponse) Descriptor() ([]byte, []int) {
	return file_proto_nominatim_proto_rawDescGZIP(), []int{1}
}

func (x *ListNominatimResponse) GetNominatimresponse() []*NominatimResponseItem {
	if x != nil {
		return x.Nominatimresponse
	}
	return nil
}

type QueryString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryString) Reset() {
	*x = QueryString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nominatim_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryString) ProtoMessage() {}

func (x *QueryString) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominatim_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryString.ProtoReflect.Descriptor instead.
func (*QueryString) Descriptor() ([]byte, []int) {
	return file_proto_nominatim_proto_rawDescGZIP(), []int{2}
}

func (x *QueryString) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type NominatimResponseItem_BoundingboxArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NominatimResponseItem_BoundingboxArray) Reset() {
	*x = NominatimResponseItem_BoundingboxArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nominatim_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NominatimResponseItem_BoundingboxArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NominatimResponseItem_BoundingboxArray) ProtoMessage() {}

func (x *NominatimResponseItem_BoundingboxArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominatim_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NominatimResponseItem_BoundingboxArray.ProtoReflect.Descriptor instead.
func (*NominatimResponseItem_BoundingboxArray) Descriptor() ([]byte, []int) {
	return file_proto_nominatim_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NominatimResponseItem_BoundingboxArray) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_nominatim_proto protoreflect.FileDescriptor

var file_proto_nominatim_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98,
	0x03, 0x0a, 0x15, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4f, 0x73, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f,
	0x73, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x73, 0x6d, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4f, 0x73, 0x6d, 0x49, 0x44, 0x12, 0x4f, 0x0a, 0x0b,
	0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x62, 0x6f, 0x78, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x62, 0x6f, 0x78, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x52, 0x0b, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x62, 0x6f, 0x78, 0x12, 0x10, 0x0a,
	0x03, 0x4c, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f,
	0x6e, 0x1a, 0x26, 0x0a, 0x10, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x62, 0x6f, 0x78,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x11, 0x6e, 0x6f, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23,
	0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x32, 0x4c, 0x0a, 0x10, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_nominatim_proto_rawDescOnce sync.Once
	file_proto_nominatim_proto_rawDescData = file_proto_nominatim_proto_rawDesc
)

func file_proto_nominatim_proto_rawDescGZIP() []byte {
	file_proto_nominatim_proto_rawDescOnce.Do(func() {
		file_proto_nominatim_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_nominatim_proto_rawDescData)
	})
	return file_proto_nominatim_proto_rawDescData
}

var file_proto_nominatim_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_nominatim_proto_goTypes = []interface{}{
	(*NominatimResponseItem)(nil),                  // 0: proto.NominatimResponseItem
	(*ListNominatimResponse)(nil),                  // 1: proto.ListNominatimResponse
	(*QueryString)(nil),                            // 2: proto.QueryString
	(*NominatimResponseItem_BoundingboxArray)(nil), // 3: proto.NominatimResponseItem.BoundingboxArray
}
var file_proto_nominatim_proto_depIdxs = []int32{
	3, // 0: proto.NominatimResponseItem.Boundingbox:type_name -> proto.NominatimResponseItem.BoundingboxArray
	0, // 1: proto.ListNominatimResponse.nominatimresponse:type_name -> proto.NominatimResponseItem
	2, // 2: proto.NominatimService.List:input_type -> proto.QueryString
	1, // 3: proto.NominatimService.List:output_type -> proto.ListNominatimResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_nominatim_proto_init() }
func file_proto_nominatim_proto_init() {
	if File_proto_nominatim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_nominatim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NominatimResponseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nominatim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNominatimResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nominatim_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nominatim_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NominatimResponseItem_BoundingboxArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_nominatim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nominatim_proto_goTypes,
		DependencyIndexes: file_proto_nominatim_proto_depIdxs,
		MessageInfos:      file_proto_nominatim_proto_msgTypes,
	}.Build()
	File_proto_nominatim_proto = out.File
	file_proto_nominatim_proto_rawDesc = nil
	file_proto_nominatim_proto_goTypes = nil
	file_proto_nominatim_proto_depIdxs = nil
}
